### ISSUE TITLE
Visual Studio "F5 experience" broken for new projects

### ISSUE THREAD

**Issue by thomyg** [OfficeDev/TeamsFx#1870]
Created a couple of fresh projects, configured SSO and pressed F5 and not one was working. I'm getting an error in Teams saying "The app you want to add doesn't exist in this org or you don't have permission to access it.

**To Reproduce**
1. Open VS and create new project
2. Configure SSO
3. Press F5

**Expected behavior**
A running default app after configuring SSO and pressing F5 aka "F5 experience"

**Screenshots**
![SNAG-0229](https://user-images.githubusercontent.com/10920072/128545935-0cc7c424-1951-4e2c-b767-e140c8ca7250.png)

**Environment**
toolkit version 0.1.50.37522
.NET 5.0
VS version 16.10.4
Windows 11 Build 22000.100
User in Ring 1.5

**Additional context**
From looking at the url that the toolkit tries to open it seems like it somehow doesn't provide the app id in the url for the installation dialogue. 

![SNAG-0230](https://user-images.githubusercontent.com/10920072/128546294-b398e119-2ee4-4297-8631-81814e359fe5.png)

From looking at the launchSeetings.json I can see a difference between the projects I created today and one example from last week (26.07.2021).

Last week:
![SNAG-0231](https://user-images.githubusercontent.com/10920072/128547442-d60beff9-9bb3-4ee4-acb4-95536bcea43f.png)

VS today:
![SNAG-0232](https://user-images.githubusercontent.com/10920072/128547462-71c770f0-fc9e-4f47-91bb-21550b5e68ae.png)

Just editing those lines in the launchSettings.json to include the actual teams app id **did not** resolve the issue.

**Comment by zhenjiao-ms** [comment]
Thanks for reporting it, @thomyg.
@nliu-ms could you please work with @JerryYangKai to see if it is the same issue as https://github.com/OfficeDev/TeamsFx/issues/1852?

**Comment by JerryYangKai** [comment]
Got it. I will investigate it and check if it caused by the api change in appstudio.

**Comment by JerryYangKai** [comment]
@thomyg  It is fixed now, please try again.
Thanks again for reporting the issue.

**Comment by thomyg** [comment]
Thank you, @JerryYangKai! Works again for newly created projects.

But do you mind explaining what changed on my end now? I still have the exact same toolkit version number on my machine. You fixed something and now it is working again. What changed under the cover, and why did it not resolve in a new toolkit version number?

**Comment by JerryYangKai** [comment]
@thomyg 
OK，I will explain it why it works. You could find all your Teams applications in this developer portal  https://dev.teams.microsoft.com/apps.
What the toolkit do is help users to create a teams app in this portal and get the return value of teamsappid though Restful API. Last week developer portal made some breaking change so this API is deprcated so you will find no teamsappid in your lauchsetting. 
What we do is let this api back to work. Also we will upgrade this api to v2 in the future to avoid this.

**Comment by eriolchan** [comment]
@thomyg thanks for continuously trying our toolkit! This is a live site incident from App Studio last Friday, and you can find more details from #1852. We have a hotfix v2.3.2 to fix this issue at that time, and you can also try it again now since this issue has been resolved from App Studio side.
