### ISSUE TITLE
Missing Add Features option

### ISSUE THREAD

**Issue by sandhyar66** [OfficeDev/TeamsFx#5623]
Issue Type: <b>Bug</b>

1. Install the latest version of VS Code
2. Install the Teams Toolkit version - 4.0.2
3. Check for Add Features option under Development, which is missing. 

Attached screenshot below for reference:
![image](https://user-images.githubusercontent.com/108132144/180933016-bd4b5883-f455-41c2-a54d-4ecd6849f064.png)

Note: Need the Add Features option.

Extension version: 4.0.2
VS Code version: Code 1.69.2 (3b889b090b5ad5793f524b5d1d39fda662b96a2a, 2022-07-18T16:12:52.460Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz (2 x 2295)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|8.00GB (3.79GB free)|
|Process Argv|--crash-reporter-id 1e0d6588-76eb-460d-b5f0-67591baae0c2|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
pylanb8912:30529769
vsclangdc:30486549
841h4636:30532337

```

</details>

**Comment by tecton** [comment]
Hi @sandhyar66, are you developing an SPFx tab project? "Add Features" is not supported for that capability now.

**Comment by sandhyar66** [comment]
@tecton , Yes I am trying to develop a personal app for Microsoft Teams. Hence, using the SPFx Tab Project. Could you please let me know if there is any other option to setup a CI/CD pipeline if the Add Features option is not supported. 

Also, please do let me know what are the projects that support the "Add Features" option.

**Comment by tecton** [comment]
You could create a Tab app to embed your existing webpage or "SSO-enabled tab" for a new one. They all support the "Add Features" option.

@IvanJobs could you please help to take a look at the CI/CD question?

**Comment by sandhyar66** [comment]
@tecton, Thanks for the update.

@IvanJobs really needed your help on setting up the CI/CD Pipeline.

**Comment by IvanJobs** [comment]
@sandhyar66 Hi, Thanks for reaching out. 
If you cannot find `Add Features` option in VS Code, don't worry. You can use Teams Toolkit CLI: https://www.npmjs.com/package/@microsoft/teamsfx-cli which can achieve the same goal to generate CI/CD pipeline templates for you.
Take the following steps and screenshot as reference:
1. `npm install -g @microsoft/teamsfx-cli` - install the latest CLI.
2. Run command `teamsfx add cicd` under your project root folder.
![image](https://user-images.githubusercontent.com/1803943/181181049-39f76900-a071-417f-bd6d-0cebc76c2fa6.png)

Please try this and any feedbacks are welcome~

**Comment by sandhyar66** [comment]
@IvanJobs, Thanks for sharing.

I have tried setting up a pipeline, but facing issue in generating a build and deploying it to the Teams using the CI/CD Pipeline.
It would be of great help if you could share the steps involved in setting up a pipeline for provisioning and deploying the  SPFx Tab Project into Microsoft Teams Application using Azure Devops. 
Since, the application for which I am trying to build the pipeline has been set up using Teams Toolkit where gulp commands will not work from the main folder.

**Note: Currently the build is been generated manually.** 

Please do the needful.

**Comment by IvanJobs** [comment]
> 

Hi @sandhyar66 great to know that you've passed the generating CI/CD templates steps.
To give a simple answer to your question, you can refer to the generated README file under `.azure/pipelines` folder to check detailed steps. You can also find the online README file for Azure DevOps in your case at https://github.com/OfficeDev/TeamsFx/tree/dev/packages/fx-core/templates/plugins/resource/cicd/azdo.

To give highlights about those steps, they are from two aspects:
1. Azure DevOps Pipelines knowledge - This is common and you can find reference links in README file or by search engines.
2. Teams Toolkit CLI knowledge - We also have official documents online: https://docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-cli and the generated CI/CD templates can be good starting examples.
Combining the two aspects together, I believe you can find your own way to build the pipelines.

Looking forward to your feedbacks~

**Comment by IvanJobs** [comment]
Since the original issue was fixed and no response for over 7 days, close this issue. If necessary, please create a new one in the future.

**Comment by Githamza** [comment]
I'm still not having the add features option . I'm using 5.4.0 version the lastest

**Comment by macik1423** [comment]
I have the same issue in version v5.4.0. I created Tab -> React with Fluent UI -> TypeScript.

**Comment by tecton** [comment]
@Githamza @macik1423 "Add Features" has been removed to increase transparency. You could click "View How-to Guides" to see which guide meets your requirement and follow the steps in it.

**Comment by Githamza** [comment]
> @Githamza @macik1423 "Add Features" has been removed to increase transparency. You could click "View How-to Guides" to see which guide meets your requirement and follow the steps in it.

Thank you . But "View how-to Guides" is not a replacement of "Add features" feature the first is docs the second apply to docs in the project without the need to read articles ^^. Anyway, thank you for your precision
